[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 3

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 4

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 5
    
# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/andrewdea"
    weight = 1

# bluesky? idk lol
# [[social]]
#     identifier = "bluesky"
#     name = "Bluesky"
#     url = "https://bsky.app/profile/outhere.bsky.social"
#     weight = 2
